FROM nvidia/cuda:11.4.3-base-ubuntu20.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.8-dev \
    python3-pip \
    libffi-dev \
    build-essential \
    rsync

ADD requirements.txt requirements.txt

RUN pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install -r requirements.txt

WORKDIR /mnt
